# Generated by Django 4.1.3 on 2022-11-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('role', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('course', models.TextField()),
                ('department', models.CharField(max_length=100, null=True)),
                ('year_of_joining', models.TextField(max_length=255)),
                ('year_of_graduation', models.TextField(max_length=255)),
                ('enrollment_no', models.IntegerField()),
            ],
        ),
    ]
