# Generated by Django 4.1.3 on 2022-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_bk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('start_date', models.TextField()),
                ('end_date', models.CharField(max_length=100, null=True)),
                ('start_time', models.TextField(max_length=255)),
                ('end_time', models.TextField(max_length=255)),
            ],
        ),
    ]
