# Generated by Django 4.1.3 on 2022-11-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_bk', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(max_length=3000)),
                ('author', models.CharField(max_length=200)),
                ('day_of_event', models.TextField(max_length=255)),
            ],
        ),
    ]
