# Generated by Django 4.1.3 on 2022-12-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_bk', '0006_usersinfo_email_usersinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='pass_year',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
